import type { Metadata } from "next";
import ClientWrapper from '../lib/ClientWrapper';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ClientWrapper>
          {children}
        </ClientWrapper>

      </body>
    </html>
  );
}
